apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-fh-blocks
spec:
  resources:
    requests:
      storage: 1T
  storageClassName: openebs-hostpath # Very small files!
  accessModes:
    - ReadWriteOnce
