apiVersion: v1
kind: Service
metadata:
  name: {{ include "mini-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mini-app.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.env.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mini-app.selectorLabels" . | nindent 4 }}
