apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 172.22.126.51
      user: k0s
      port: 22
      keyPath: ~/.ssh/k0s_rsa
    role: controller
    installFlags:
      - --debug
  - ssh:
      address: 172.22.126.52
      user: k0s
      port: 22
      keyPath: ~/.ssh/k0s_rsa
    role: controller
    installFlags:
      - --debug
  - ssh:
      address: 172.22.126.53
      user: k0s
      port: 22
      keyPath: ~/.ssh/k0s_rsa
    role: controller
    installFlags:
      - --debug
  - ssh:
      address: 172.22.1.116
      user: k0s
      port: 22
      keyPath: ~/.ssh/k0s_rsa
    role: worker
    installFlags:
    - --labels="node.k0sproject.io/role=worker"
  - ssh:
      address: 172.22.1.84
      user: k0s
      port: 22
      keyPath: ~/.ssh/k0s_rsa
    role: worker
    installFlags:
    - --labels="node.k0sproject.io/role=worker"
  - ssh:
      address: 172.22.1.85
      user: k0s
      port: 22
      keyPath: ~/.ssh/k0s_rsa
    role: worker
    installFlags:
    - --labels="node.k0sproject.io/role=worker"
  - ssh:
      address: 172.22.1.86
      user: k0s
      port: 22
      keyPath: ~/.ssh/k0s_rsa
    role: worker
    installFlags:
    - --labels="node.k0sproject.io/role=worker"
  k0s:
    version: v1.28.4+k0s.0
    dynamicConfig: true
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          externalAddress: 172.22.126.11
          sans:
            - 172.22.126.11
            - 172.22.126.51
            - 172.22.126.52
            - 172.22.126.53
          extraArgs:
            service-node-port-range: 30000-32767
        telemetry:
          enabled: true
        network:
          podCIDR: 10.96.0.0/16
          serviceCIDR: 10.10.0.0/16
          provider: custom
          kubeProxy:
            disabled: true
        extensions:
          helm:
            concurrencyLevel: 5
            repositories:
            - name: cilium
              url: https://helm.cilium.io
            charts:
            - name: cilium
              chartname: cilium/cilium
              version: "1.14.5"
              values: |
                hubble:
                  enabled: true
                  listenAddress: ":4244"
                  metrics:
                    enabled:
                      - dns
                      - drop
                      - tcp
                      - flow
                      - port-distribution
                      - icmp
                      - http
                  relay:
                    enabled: true
                  ui:
                    enabled: true
                  ipam:
                    mode: "cluster-pool"
                    operator:
                      clusterPoolIPv4PodCIDRList: 
                        - "10.96.0.0/16"
                envoy:
                  enabled: true
                kubeProxyReplacement: "strict"
                k8sServiceHost: 172.22.126.11
                k8sServicePort: 6443
                rollOutCiliumPods: true
              namespace: kube-system
