apiVersion: v1
kind: Service
metadata:
  name: relayer-svc
spec:
  type: ClusterIP
  selector:
    app: relayer
  ports:
    - name: grpc
      port: 10014
      protocol: TCP
      targetPort: 10014
    - name: prom
      port: 9102
      protocol: TCP
      targetPort: 9102
