apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firehose-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3T
  storageClassName: openebs-kernel-nfs