apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: mini-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name:mini-app
  filterTags:
    pattern: "^dev-(?P<ts>.*)"
    extract: '$ts'
  policy:
    numerical: 
      order: asc