apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: mini-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mini-app
  policy:
    semver:
      range: 0.0.x