apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cubefs
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/cubefs/cubefs-helm
  ref:
    branch: master

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cubefs
  namespace: cubefs
  annotations:
    helm.fluxcd.io/uninstall: true
spec:
  interval: 6h
  chart:
    spec:
      chart: ./cubefs
      sourceRef:
        kind: GitRepository
        name: cubefs
  targetNamespace: cubefs
  install:
    createNamespace: true
  values:
    csi:
      kubeletPath: /var/lib/k0s/kubelet
    master:
      replicas: 1
    objectnode:
      replicas: 1
    blobstore:_clustermgr:
      replicas: 1
    blobstore_scheduler:
      replicas: 1