apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
sortOptions:
  order: fifo
resources:
  - weave.yaml # Flux dashboard
  - reloader.yaml # Reloader
  # - metallb.yaml # Load balancer
  # - ../configs/metallb/
  # - traefik.yaml # Ingress Traefik
  # - cubefs.yaml

  # - loki-stack.yaml               # Logs (non-distributed)
  # - loki.yaml                     # Logs (distributed)
  # - tempo.yaml                    # Traces
  # - otel.yaml                     # OpenTelemetry
  # - prometheus.yaml                 # Metrics
  # - thanos.yaml
  # - odigos.yaml                   # Instrumentation
  # - fluent.yaml                   # K8s logs transmission
  # - openebs.yaml # Dynamic storage
  # - keda.yaml                     # Horizontal autoscaling
  # - vpa.yaml                      # Vertical autoscaling
  # - secrets.yaml # Sealed secrets
  # - mayastor.yaml                   # Storage engine
  # - nfs-provisioner.yaml             # multi-node storage access
