---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 6h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
  annotations:
    helm.fluxcd.io/uninstall: true
spec:
  interval: 6h
  chart:
    spec:
      chart: loki-distributed
      version: "0.78.2"
      sourceRef:
        kind: HelmRepository
        name: loki
  targetNamespace: monitoring
  install:
    createNamespace: true
  values:
    querier:
      replicas: 2
      maxUnavailable: 1
      persistance:
        enabled: true
        size: 10Gi
        storageClass: openebs-kernel-nfs
    distributor:
      replicas: 3
      maxUnavailable: 2
    ingester:
      replicas: 3
      maxUnavailable: 2
      persistence:
        enabled: true
        inMemory: false
        claims:
          - name: data
            size: 10Gi
            storageClass: openebs-kernel-nfs
    queryFrontend:
      replicas: 2
      maxUnavailable: 1
    gateway: 
      replicas: 2
      maxUnavailable: 1
    compactor:
      kind: StatefulSet
      replicas: 1
      enabled: true
      persistence: 
        enabled: true
        claims:
          - name: data
            size: 10Gi
            storageClass: openebs-kernel-nfs
    ruler:
      enabled: true
      replicas: 2
      maxUnavailable: 1    
    indexGateway:
      enabled: true
      replicas: 2
      maxUnavailable: 1
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
      namespace: monitoring       

          