apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBg0IhkoIAQM9jFxIQvpiibhkTT8Vbd7MtCaVjoZIblX8rCHnnQozekIHuqQMmxDoEcVGLY540oUf/G4AfZXwM55r3ABynP+Y4/v0yuKQNwF/fH+9Wx1k5tDIz6ACwVe2A2lXZ9J47iXB6tBRH8KygWkLxwY4FurGKGSDMPY2L6yW4PLqZrA5nX4v6yg9yilVqKIqqtDoXoQrfnaO/l4xIf/O/CL+QnulN1GpnqxI/6TG8CDNJAW/WZOqyOUIv/YkSvQNMah5KupEiRy1nARQa8sufZ0ljpI33lCukSkZ0dcOE33Fykezwdi3gffUlY+Pe1TI4ZktiyUV7P/4qyvM8eJfNNZTm/u5H8iW5MUtqY8nZgLb1V88EC87nw2jpQ4Hl6pTUS++PmOz4lDDD41+1324dqM3twGx1n3InBhWvdV+yvWCp7arIdQEWhcYMX77trTN5VNz2NdJGmIzx/flPFD/HcdMvlbFnG2RimKFebOr3w7/jJdqQ1Gb0/6W2DpddOHjOhaygNjabFJiFZCC1EcpRw2prQA+KyntcUhxu8J7hxskAhsnYclSaJPIuIFE3JIz8HPktV/FbBHFVvWRGF2rYKOpjj3e40ifz0QDZD1aLU8vR75wUVyb4t3r6boHXAd+iZR1PQPK1FrJ4YZmjWeCMDXTwTsahPFurljombcy1ohN/ifTEXtTmdIwjoECZJSnaUOg==
    admin-user: AgALLiYd/Gmxjqq26cmvuPXB6P+TxpYsVg3w2sOtB6Fh5mdEZxtAkG+fj5a2dabuJOw4UEinRZTE4q1zTnrJEtUB0wZHUT/7wKfJzMnBMYI7RmidYoeQdaA6sEsjaZXIM7OXOwszYJPtj487kmd+OfownGNRO7DYfU07FsYfw53adre0IYYXvxvlLvdlmL4XrMbB5M0UoG0N8PsDXF2GA+BB7UIjJaj6be4tOsOQLw7TGPCl+FmTdz4KJPNKTv35gE44yFtbNVCGcPWdNjXmXpK5uUtJdnIuV5AW4b+5gvc+5MOy41s4ZP1Z9lAJiEGusYXHM+nzuMuho0JcNcJKZMtjWzRjjooG+jYd0OV8+RvXfbTlx8psPzR3cOD4HiqQI/3jtifz//Ss+VmmBLG2hKTZLPfRanzCNNH81+no1rL0S22GQSRQEyLcr/q7fAGsxaE3gIRyzx32pIY2wpPwzM63QLstWIYk1DBrZ47wy/T+s0snIq1UwLjpHKYg3absU5iagwX1y2MbXAJPILYErLn6r9GX5p+jMybh5WPgf0uHC3FmXryx0FfA92+pZIMonvGaK+/cNxLd3+I062qtTocm+AlCnYshGVf2CQJ8Il7wzaVPPjMcInZgYOcGXcQC3jVAvBsbiIZ/CAlr/h9Vv7v8v9cinFRFxcMsmvKjiefA0MGO2IcRU2r/63H25jWMuGeI7kzJow==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque