apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "nimbus-nodeports"
spec:
  nodeSelector: {}
  description: "Nimbus NodePorts"
  ingress:
    - toPorts:
        - ports:
            - port: "31000"
              protocol: TCP
            - port: "31000"
              protocol: UDP
