apiVersion: v1
kind: Service
metadata:
  name: firehose-svc
spec:
  type: ClusterIP
  selector:
    app: firehose
  ports:
    - name: live-blocks
      port: 10014
      protocol: TCP
      targetPort: 10014
    - name: grpc
      port: 10015
      protocol: TCP
      targetPort: 10015
    - name: prom
      port: 9102
      protocol: TCP
      targetPort: 9102
