apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "fh-eth-nodeports"
spec:
  nodeSelector: {}
  description: "Firehose geth NodePorts"
  ingress:
    - toPorts:
        - ports:
            - port: "30310"
              protocol: TCP
            - port: "30310"
              protocol: UDP
