# Firehose reader data. Should mostly be temp files, including the "work dir".
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reader
spec:
  resources:
    requests:
      storage: 1G
  storageClassName: openebs-hostpath
  accessModes:
    # To be shared with the merger node
    - ReadWriteOnce

---
# Ethereum node data (Geth full node).
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reader-node
spec:
  resources:
    requests:
      storage: 1T
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
