---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mini-app
  namespace: flux-system
spec:
  interval: 2m
  url: https://coutug.github.io/test-cluster/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mini-app
  namespace: flux-system
  annotations:
    helm.fluxcd.io/uninstall: true
spec:
  releaseName: mini-app
  interval: 6h
  chart:
    spec:
      chart: mini-app
      version: 1.0.4
      sourceRef:
        kind: HelmRepository
        name: mini-app
  targetNamespace: mini-app
  install:
    createNamespace: true
