---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - setup
  # - reader-node
  # - merger
  # - relayer
  # - indexer
  # - firehose
  # - nimbus
  # - seaweedfs
  - substreams-tier1
  - substreams-tier2

images:
  - name: fireeth
    newName: ghcr.io/streamingfast/firehose-ethereum
    newTag: v2.0.2-geth-v1.13.5-fh2.3
