apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-ext4
parameters:
  ioTimeout: "30"
  protocol: nvmf
  repl: "1"
  fstype: ext4
provisioner: io.openebs.csi-mayastor
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-xfs
parameters:
  ioTimeout: "30"
  protocol: nvmf
  repl: "1"
  fstype: xfs
provisioner: io.openebs.csi-mayastor