---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-default
value: 100000
globalDefault: true
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-high
value: 1000
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-normal
value: 100
globalDefault: false