---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops-repo
  namespace: flux-system
spec:
  type: oci
  interval: 60m0s
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops-release
  namespace: flux-system
spec:
  interval: 60m
  chart:
    spec:
      chart: weave-gitops
      version: "4.0.32"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-repo
      interval: 12h
  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1
        memory: 512Mi
    adminUser:
      create: true
      username: admin
      passwordHash: "$2a$10$OMFLoP1rL2uOqtfcrfDuD.Y8gPTLmGCJ9yGd28vP53sBthGkKa5j2"
    service:
      create: true
      type: NodePort
      port: 9001
      nodePort: 30022
      annotations: {}