apiVersion: v1
kind: Service
metadata:
  name: indexer-svc
spec:
  type: ClusterIP
  selector:
    app: indexer
  ports:
    - name: grpc-healthz
      port: 10009
      protocol: TCP
      targetPort: 10009
    - name: prom
      port: 9102
      protocol: TCP
      targetPort: 9102