apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-app
  # namespace: app
  labels:
    app: mini-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini-app
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 1
  #     maxSurge: 1
  template:
    metadata:
      labels:
        app: mini-app
    spec:
      containers:
      - name: mini-app
        image: ghcr.io/coutug/mini-app:0.0.5 # {"$imagepolicy": "flux-system:mini-app"}
        ports:
        - containerPort: 8000
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
          # env:
          # - name: ENV_VAR1
          #   value: "valeur1"
          # - name: ENV_VAR2
          #   valueFrom:
          #     configMapKeyRef:
          #       name: ma-config-map
          #       key: cle-config
          # volumeMounts:
          # - name: mon-volume
          #   mountPath: /chemin/dans/conteneur
      # volumes:
      # - name: mon-volume
      #   configMap:
      #     name: ma-config-map
